name: Build Aeolus plugin

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
              name: "Windows Latest",
              os: windows-latest,
              build_type: Release
            }
          - {
              name: "Ubuntu Latest",
              os: ubuntu-latest,
              build_type: Release
            }

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Ninja
      if: matrix.config.os == 'windows-latest'
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install Linux dependencies
      if: matrix.config.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libx11-dev libfreetype-dev libasound2-dev libxrandr-dev libxinerama-dev libxcursor-dev

    - name: Compile Windows
      if: matrix.config.os == 'windows-latest'
      shell: cmd
      run: |
        mkdir build
        cd build
        call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
        cmake ../ -G Ninja -D WITH_ASIO=OFF -D CMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
        cmake --build .

    - name: Compile Linux
      if: matrix.config.os == 'ubuntu-latest'
      run: |
        mkdir -p build
        cd build
        cmake ../ -D WITH_ASIO=OFF -D CMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
        cmake --build .
