name: Build Aeolus plugin

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

env:
  type: Release
  dir_build: ./build
  dir_source: .

jobs:
  build:
    name: All platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]
        include:
          - os: ubuntu-latest
            name: linux
            generator: Unix Makefiles
            path: ./build/Aeolus_artefacts
          - os: macos-latest
            name: mac
            generator: Unix Makefiles
            path: ./build/Aeolus_artefacts
          - os: windows-2019
            name: win
            generator: Visual Studio 16 2019
            path: ./build/Aeolus_artefacts/Release

    steps:
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install ninja-build libx11-dev libfreetype-dev libasound2-dev libxrandr-dev libxinerama-dev libxcursor-dev

    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: brew install ninja

    - name: Install Windows dependencies
      if: matrix.os == 'windows-2019'
      run: choco install ninja

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build plugin
      run: |
        cmake \
          -G "${{ matrix.generator }}" \
          -DWITH_ASIO=OFF \
          -S "${{ env.dir_source }}" \
          -B "${{ env.dir_build }}"
        cmake --build "${{ env.dir_build }}" --config "${{ env.type }}"

    - name: List errors
      run: cat "${{ env.dir_build }}/CMakeFiles/CMakeError.log" || true

    - name: List files generated
      run: |
        cd ${{ matrix.path }}
        find "$(pwd)"

    - uses: actions/upload-artifact@v3
      with:
        name: aeolus-${{ matrix.name }}
        path: ${{ matrix.path }}
