name: Build Aeolus plugin

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
              name: "Windows Latest",
              os: windows-latest,
              build_type: Release
            }
          - {
              name: "Ubuntu Latest",
              os: ubuntu-latest,
              build_type: Release
            }

    steps:
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile
      run: |
        mkdir build
        cd build
        cmake ../ -G Ninja -D CMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
        cmake --build .
